config/routes.rb
MyAppName::Application.routes.draw do
  
  devise_for :users
  resources :users

  resources :admin, :as => "admin", :only => [:index] do
    collection do
    end
  end

  get 'about' => 'main#about'
  post 'feedback' => 'main#feedback'

  root :to => 'main#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  # Not yet: :database_authenticatable, :recoverable, :validatable, 
  devise :rememberable, :trackable, :token_authenticatable #, :registerable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  # Default Behaviour: Work only with elements that has not been logically excluded
  default_scope where(:excluded => false)

  # Generate token unless one exists
  before_save :ensure_authentication_token
end

app/controllers/admin_controller.rb
# encoding: utf-8
class AdminController < ApplicationController

  # Autenticação básica, só pra começar - Para todos os métodos deste controller
  http_basic_authenticate_with :name => "admin123", :password => "admin123"
  
  # GET /admin
  def index
  end

end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery

  require 'constants'

  # Devise overriding
  def after_sign_in_path_for(user)
    user_root_path
  end

  # Devise overriding
  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/main_controller.rb
# encoding: utf-8
class MainController < ApplicationController

  # GET /
  def home
  end

  # GET /about
  def about
  end

  # POST /feedback
  def feedback
    # Tell the UserMailer to send admins the feedback email
    UserMailer.admin_feedback_email(params[:email], params[:feelings], params[:feedback]).deliver

    # Also tell the UserMailer to send a thankyou email if the user left a valid email address
    UserMailer.user_feedback_email(params[:email]).deliver if params[:email]

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Thanks for your feedback.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:excluded, true)

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<%= content_for :title do %>Admin<% end %>

<h1>Admin View</h1>
<br/>

<div class="accordion" id="accordion">
  Lorem Ipsum
</div>

<span class="pull-right muted">
  Lorem Ipsum
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= APP_NAME %> - <%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your Description">
    <meta name="author" content="Your Name">
    <meta name="keywords" content="Your Keywords"/>
  
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <style>
      /* Workaround for Sticky footer + Fixed Top Nav Bar */
      .container-main {
        padding-top: 60px;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
    -->
  </head>

  <body>

    <div id="feedback" class="hidden-phone">
      <a href="#feedback-panel" role="button" data-toggle="modal">feedback</a>
    </div>

    <!-- Feedback Modal -->
    <div id="feedback-panel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <%= form_tag feedback_url, id: "feedback_form" do %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Tell us what you think</h3>
        </div>
        <div class="modal-body" >
          
            <fieldset>
              <textarea id="txt-feedback" rows="3" class="required" style="width: 500px;" name="feedback" placeholder="Feedback..."></textarea>

              <% if user_signed_in? %>
                <input type="hidden" name="email" value="<%= current_user.email %>">
              <% else %>
                <div class="input-prepend">
                  <span class="add-on">E-mail</span>
                  <input class="span2" id="prependedInput" type="email" name="email" placeholder="Your e-mail [optional]">
                </div>
              <% end %>
            
            </fieldset>
            
            <!--
            <label class="radio inline">
              <input type="radio" name="feelings" id="optionsRadios1" value="I-Like-It" checked>
              I like it
            </label>
          
            <label class="radio inline ">
              <input type="radio" name="feelings" id="optionsRadios2" value="I-Dont-Like-It">
              I don't like it
            </label>
            -->
        </div>
        <div class="modal-footer">
          <button id="btn-submit-feedback" type="submit" class="btn btn-primary">Submit feedback</button>
          <button class="btn btn-link btn-small pull-left" data-dismiss="modal" aria-hidden="true">Cancel</button>
        </div>
      <% end %>
    </div>

    <!-- Part 1: Wrap all page content here -->
    <div id="wrap">

      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <%= link_to APP_NAME, root_url, class: "brand" %>
            <div class="nav-collapse collapse">
              <% if user_signed_in? %>
                <p class="navbar-text pull-right">
                  <small><%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></small>
                </p>
              <% else %>
                <p class="navbar-text pull-right">
                  <small><%= link_to "Login", new_user_session_path %></small>
                </p>
              <% end %>
              <ul class="nav">
                <li class="<%= 'active' if params[:action] == 'home' %>"> <%= link_to "Home", root_url %> </li>                
                <li class="<%= 'active' if params[:action] == 'index' %>"> <%= link_to "Something", users_url %> </li>
                <li class="<%= 'active' if params[:action] == 'about' %>"> <%= link_to "About", about_url %> </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="container container-main">

        <% if alert %>
          <div id="alert" class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= alert %>
          </div>
        <% end %>

        <% if notice %>
          <div id="notice" class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= notice %>
          </div>
        <% end %>

        <%= yield %>

      </div> <!-- /container -->

      <div id="push"></div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="muted credit">Proudly made in Somewhere, Brasil.</p>
      </div>
    </div>

  <!-- Clicky Tracking Code -->
  <script src="//static.getclicky.com/js" type="text/javascript"></script>
  <script type="text/javascript">try{ clicky.init(<%= CLICKY_CODE %>); }catch(e){}</script>
  <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/<%= CLICKY_CODE %>ns.gif" /></p></noscript>

  </body>
</html>

app/views/main/about.html.erb
<%= content_for :title do %>About<% end %>

<div class="hero-unit">
  <h1>About <%= APP_NAME %></h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<br/>
  </p>
  <p>
    <a class="btn btn-primary btn-large" href="/">
      Back home
    </a>
  </p>
</div>

app/views/main/home.html.erb
<%= content_for :title do %>My Home Title<% end %>

<div class="hero-unit">
  <h1><%= APP_NAME %></h1>
  <p>
    Lorem ipsum dolor<br/>
    sit amet, consectetur adipisicing elit<br/>
  </p>
  <p>
    <%= link_to "Start Now", "#", class: "btn btn-primary btn-large" %>
  </p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-horizontal", id: "my_form"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name, class: "required", minlength: "2" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, class: "control-label" %>
    <div class="controls">
      <%= f.email_field :email, class: "required email" %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit(nil, class:"btn btn-primary btn-large") %> or <%= link_to 'Return', users_path, class: "text-error" %>
    </div>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<%= content_for :title do %>Editing User<% end %>

<h1>Editing User</h1>
<br/>

<%= render 'form' %>

app/views/users/index.html.erb
<%= content_for :title do %>Users<% end %>

<h1>Users</h1>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to '<i class="icon-zoom-in"></i>'.html_safe, user %></td>
    <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_user_path(user) %></td>
    <td><%= link_to '<i class="icon-trash"></i>'.html_safe, user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br/><br/>

<%= link_to 'New user', new_user_path, class: "btn btn-primary btn-large" %>

app/views/users/new.html.erb
<%= content_for :title do %>New User<% end %>

<h1>New User</h1>
<br/>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Excluded:</b>
  <%= @user.excluded %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= content_for :title do %><%= @user.name %><% end %>

<legend><%= @user.name %><span class="muted pull-right"><small><em><%= @user.email %></em></small></span></legend>

<p class="lead">
  <span class="app_status" action="">
    <%= @user.name %>
  </span>
  <span class="loading hidden"><%= image_tag "loading.gif" %></span>
</p>
<p id="time_ago" class="muted"><small><em>Created <%= time_ago_in_words(@user.created_at) %> ago.</em></small></p>

<br/><br/>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-large" %>
<br/>